In [3]:
%load_ext autoreload
# %autoreload 2

In [4]:
%autoreload 2
from src import matriz_aumentada, gauss_jordan

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b) # type: ignore
gauss_jordan(Ab)

[02-04 12:14:32][INFO][hp] 2026-02-04 12:14:32.715168
[02-04 12:14:32][INFO][hp] 2026-02-04 12:14:32.721592
[02-04 12:14:32][INFO][hp] 2026-02-04 12:14:32.727974
[02-04 12:14:32][INFO][hp] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[02-04 12:14:32][INFO][hp] 
[[ 1.  0.  3.  6.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[02-04 12:14:32][INFO][hp] 
[[ 1.  0.  0. -3.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
[02-04 12:14:32][INFO][hp] 
[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0. -6.]
 [ 0.  0. -1.  0. -6.]
 [ 0.  0.  0.  2. -4.]]


array([ 3., -6.,  6., -2.])

# Resolver

In [5]:
import logging
from sys import stdout
from datetime import datetime
import os

logging.basicConfig(
    level=logging.INFO,
    format=f"[%(asctime)s][%(levelname)s][{os.environ.get('USERNAME')}] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[02-04 12:14:35][INFO][hp] 2026-02-04 12:14:35.261702


In [ ]:
import numpy as np

def inv_matrix(A: np.ndarray) -> np.ndarray:
    """
    Inversión de una matriz cuadrada mediante Gauss-Jordan,
    usando la función gauss_jordan del recurso.
    """
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)

    n = A.shape[0]
    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."

    A_inv = np.zeros((n, n))

 
    for i in range(n):
        e = np.zeros(n)
        e[i] = 1  

        # matriz aume
        Ab = np.hstack((A, e.reshape(-1, 1)))

        # resol
        xi = gauss_jordan(Ab)

        A_inv[:, i] = xi

    return A_inv


## Ejemplos
* Ejemplo 1

In [12]:
# La matriz A =
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]
inv_matrix(A)

[02-04 12:15:27][INFO][hp] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -2.]
 [ 0.  0. -1. -3. -3.]
 [ 0. -1. -3. -6. -4.]]
[02-04 12:15:27][INFO][hp] 
[[ 1.  0.  3.  6.  5.]
 [ 0.  1.  0. -1. -2.]
 [ 0.  0. -1. -3. -3.]
 [ 0.  0. -3. -7. -6.]]
[02-04 12:15:27][INFO][hp] 
[[ 1.  0.  0. -3. -4.]
 [ 0.  1.  0. -1. -2.]
 [ 0.  0. -1. -3. -3.]
 [ 0.  0.  0.  2.  3.]]
[02-04 12:15:27][INFO][hp] 
[[ 1.   0.   0.   0.   0.5]
 [ 0.   1.   0.   0.  -0.5]
 [ 0.   0.  -1.   0.   1.5]
 [ 0.   0.   0.   2.   3. ]]
[02-04 12:15:27][INFO][hp] 
[[ 1.  2.  3.  4.  0.]
 [ 0.  1.  0. -1.  1.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[02-04 12:15:27][INFO][hp] 
[[ 1.  0.  3.  6. -2.]
 [ 0.  1.  0. -1.  1.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7.  1.]]
[02-04 12:15:27][INFO][hp] 
[[ 1.  0.  0. -3. -2.]
 [ 0.  1.  0. -1.  1.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2.  1.]]
[02-04 12:15:27][INFO][hp] 
[[ 1.   0.   0.   0.  -0.5]
 [ 0.   1.   0.   0.   1.5]
 [ 0.   0.  -1.   0.   1.5]
 [ 0.   0.   0.   2. 

array([[ 0.5, -0.5, -1.5,  1.5],
       [-0.5,  1.5, -1.5,  0.5],
       [-1.5, -1.5,  3.5, -1.5],
       [ 1.5,  0.5, -1.5,  0.5]])

* Ejemplo 2

In [8]:
# La matriz A =
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
inv_matrix(A)

[02-04 12:14:51][INFO][hp] Intercambiando filas 0 y 2.
[02-04 12:14:51][INFO][hp] 
[[ 2.   1.   4.   1.   0. ]
 [ 0.   2.5 -4.   0.5  0. ]
 [ 0.   2.  -3.  -1.   1. ]
 [ 0.   0.5 -1.   2.5  0. ]]
[02-04 12:14:51][INFO][hp] Intercambiando filas 1 y 3.
[02-04 12:14:51][INFO][hp] 
[[  2.    0.    6.   -4.    0. ]
 [  0.    0.5  -1.    2.5   0. ]
 [  0.    0.    1.  -11.    1. ]
 [  0.    0.    1.  -12.    0. ]]
[02-04 12:14:51][INFO][hp] 
[[  2.    0.    0.   62.   -6. ]
 [  0.    0.5   0.   -8.5   1. ]
 [  0.    0.    1.  -11.    1. ]
 [  0.    0.    0.   -1.   -1. ]]
[02-04 12:14:51][INFO][hp] 
[[  2.    0.    0.    0.  -68. ]
 [  0.    0.5   0.    0.    9.5]
 [  0.    0.    1.    0.   12. ]
 [  0.    0.    0.   -1.   -1. ]]


array([[-34.,   0.,   0.,   0.],
       [ 19.,   0.,   0.,   0.],
       [ 12.,   0.,   0.,   0.],
       [  1.,   0.,   0.,   0.]])

## Ejercicios

* Ejercicio 1

In [14]:
import  numpy as np

A = [[2, -3], [-1, 1]]
#Comprobacion
#np.linalg.inv(A)
#metodo de la inversa con gauss jordan
inv_matrix(A)

[02-04 12:18:01][INFO][hp] Intercambiando filas 0 y 1.
[02-04 12:18:01][INFO][hp] 
[[-1.  1.  0.]
 [ 0. -1.  1.]]
[02-04 12:18:01][INFO][hp] 
[[-1.  0.  1.]
 [ 0. -1.  1.]]
[02-04 12:18:01][INFO][hp] Intercambiando filas 0 y 1.
[02-04 12:18:01][INFO][hp] 
[[-1.  1.  1.]
 [ 0. -1.  2.]]
[02-04 12:18:01][INFO][hp] 
[[-1.  0.  3.]
 [ 0. -1.  2.]]


array([[-1., -3.],
       [-1., -2.]])

* Ejercicio 2

In [16]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
#np.linalg.inv(A)
inv_matrix(A)

[02-04 12:19:46][INFO][hp] Intercambiando filas 0 y 1.
[02-04 12:19:46][INFO][hp] 
[[  1.   0.   4.   0.   0.]
 [  0.   0. -16.   5.   1.]
 [  0.   4. -11.   3.   0.]
 [  0.   3.  -1.   0.   0.]]
[02-04 12:19:46][INFO][hp] Intercambiando filas 1 y 3.
[02-04 12:19:46][INFO][hp] 
[[  1.           0.           4.           0.           0.        ]
 [  0.           3.          -1.           0.           0.        ]
 [  0.           0.          -9.66666667   3.           0.        ]
 [  0.           0.         -16.           5.           1.        ]]
[02-04 12:19:46][INFO][hp] 
[[ 1.          0.          0.          1.24137931  0.        ]
 [ 0.          3.          0.         -0.31034483  0.        ]
 [ 0.          0.         -9.66666667  3.          0.        ]
 [ 0.          0.          0.          0.03448276  1.        ]]
[02-04 12:19:46][INFO][hp] 
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -3.60000000e+01]
 [ 0.00000000e+00  3.00000000e+00  0.00000000e+00  0.0

array([[-36.,  45.,  60., -80.],
       [  3.,  -4.,  -5.,   7.],
       [  9., -11., -15.,  20.],
       [ 29., -36., -48.,  64.]])

* Ejercicio 3

In [9]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
inv_matrix(A)

* Ejercicio 4

In [10]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
inv_matrix(A)